#!/bin/bash

# get Master state (on/off)
STATE="$(amixer get Master | grep Left:)"
STATE=${STATE##*[}
STATE=${STATE%]*}
STATE=${STATE^^}

# set up/down/mute
case $1 in
	u)
		AUX="$(amixer set Master 5%+ | grep Left:)"
		;;
	d)
		AUX="$(amixer set Master 5%- | grep Left:)"
		;;
	m)
		AUX="$(amixer get Master | grep Left:)"
		# switch mute
		case $STATE in
			ON)
				amixer set Master off
				STATE="OFF"
				;;
			OFF)
				amixer set Master on
				STATE="ON"
				;;
		esac
		;;
	*)
		echo "Usage: $0 {u|d|m}"
		exit
		;;
esac

# extract volume value from AUX
AUX=${AUX#*[}
AUX=${AUX%%]*}

# compose output
OUT="[${STATE}] VOLUME: ${AUX}"

# kill previous task
killall aosd_cat &> /dev/null

# show
echo "$OUT" | aosd_cat -n "Sans 25" --back-color=#404040 -b 255 -d 10 --fore-color=#e0e0e0 --shadow-opacity=0 -u 1000 -o 1000
